-- ============================================================================
--  Restore the 2026/2027 Semester 2 registration of MRU2026004388
--  NAKAFEERO MASTULAH — BED(P), in-service, Year 1
--  Muteesa I Royal University                                     2026-08-27
--
--  WHAT HAPPENED
--  -------------
--  On 18 May 2026 she was registered TWICE, under two different academic years:
--
--    09:45:42  billed 434,000 for 2026/2027 Term 2      <- the real registration
--    09:47:49  registered 10 courses, ACAD=2026/2027 SEM=2
--    11:39:21  billed 434,000 again, this time 2025/2026 Term 2   <- duplicate
--    11:40:31  registered 9 of the same courses, ACAD=2025/2026 SEM=2
--    17:36:55  her semester-deletion request (raised 15 May, "I've not selected
--              courses") was approved by muhindo and executed against
--              2025/2026 sem 2 — correctly removing the DUPLICATE.
--
--  So the duplicate was cleaned up as intended. What is unexplained is that her
--  genuine 2026/2027 registration and its 10 courses are also gone: no deletion
--  request covers that year, the approval handler is scoped to the year in the
--  request, no activity-log entry records their removal, and they are absent
--  from every deletion backup table (acad_registration_regdel_bak,
--  acad_registration_2627phantom_bak, reg_cleanup_20260711_deleted_regs,
--  reg_perfect_20260711_deleted). They were removed without an audit trail.
--
--  Then on 27 Aug 2026 15:37 the surviving 2026/2027 BILLS were deleted by
--  Muhindo mubaraka as "System Error / AUTO Billing Mistake", leaving only the
--  2025/2026 duplicate bills. That is the wrong way round — 2026/2027 is the
--  year she actually studied — but the amounts are identical (280,000 tuition +
--  154,000 function = 434,000), so her balance is unaffected.
--
--  EVIDENCE FOR WHAT TO RESTORE
--  ----------------------------
--  1. acad_activity_log logids 220235-220244 record all ten course registrations
--     with ACAD=2026/2027, SEM=2, timestamped 2026-05-18 09:47:49.
--  2. Her examination permit, generated by this system, reads "Year 1 Session 2,
--     2026/2027", "Reg. Status: Registered", and lists exactly those ten courses.
--     Its financials — Bill 434,000, Paid 464,000, Outstanding -30,000, 106.9% —
--     match her ledger exactly.
--  3. All ten are genuine BED(P) year 1 semester 2 curriculum courses.
--  4. Her cohort peers (MRU2026004387, ...4437, ...4521, ...4582, ...4597,
--     ...4598) are registered 2026/2027 sem 2 study year 1, billed 434,000 under
--     2026/2027 sem 2. Her restored rows are modelled on MRU2026004387.
--
--  MARKS ARE NOT RESTORED — they were never entered. Her cohort's marks for
--  these courses were captured and published between 10 and 26 August 2026,
--  months after her registration disappeared, so she was absent from every mark
--  sheet. Nothing in any table, backup or audit trail holds a mark for her. Her
--  scripts must be recovered from the faculty's paper records; the courses are
--  restored here in NOT_ENTERED state so the marks can be captured normally.
--
--  Safe to re-run: every insert is guarded by NOT EXISTS.
-- ============================================================================

SET @reg  := 'MRU2026004388';
SET @year := '2026/2027';
SET @sem  := 2;
SET @sy   := 1;
SET @actor:= 'restore-registration-20260827';

-- ---------------------------------------------------------------------------
-- 0. Backup of the finance rows this script re-tags.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campus_dynamics.bk_restore4388_fees_20260827 AS
SELECT * FROM campus_dynamics_accounts.fin_studentfeestracking WHERE 1 = 0;

INSERT INTO campus_dynamics.bk_restore4388_fees_20260827
SELECT f.* FROM campus_dynamics_accounts.fin_studentfeestracking f
 WHERE TRIM(f.regno) = @reg
   AND NOT EXISTS (SELECT 1 FROM campus_dynamics.bk_restore4388_fees_20260827 b
                    WHERE b.TID = f.TID);

-- ---------------------------------------------------------------------------
-- 1. The semester registration.
--    registeredBy must not start with AUTO-/AUTO_/RECON-/RECON_/AUTORECON/
--    SYSTEM_ — trigger trg_acadreg_block_autoreg rejects those by policy.
-- ---------------------------------------------------------------------------
INSERT INTO campus_dynamics.acad_registration
       (regno, acad_year, semester, regstatus, studyyear,
        id_cardStatus, residence_status, reg_CardStatus, examClearance,
        clearedBy, registeredBy, conducted_new_registration)
SELECT @reg, @year, @sem, 'REGISTERED', @sy,
       '-', '-', '-', 'UNCLEARED', '-', @actor, 'Yes'
  FROM DUAL
 WHERE NOT EXISTS (
        SELECT 1 FROM campus_dynamics.acad_registration r
         WHERE TRIM(r.regno) = @reg AND r.acad_year = @year AND r.semester = @sem);

-- ---------------------------------------------------------------------------
-- 2. The ten course registrations, exactly as the activity log records them.
--    Left in NOT_ENTERED so marks can be captured through the normal workflow.
-- ---------------------------------------------------------------------------
DROP TEMPORARY TABLE IF EXISTS tmp_restore_courses;
CREATE TEMPORARY TABLE tmp_restore_courses (course_code VARCHAR(30) NOT NULL);
INSERT INTO tmp_restore_courses (course_code) VALUES
  ('BEF1204B'),  -- Contemporary Education System
  ('BCU1204B'),  -- Curriculum Design and Implementation
  ('BGC1203B'),  -- Educational Guidance and Counselling
  ('BMA1201B'),  -- Educational Management & Administration
  ('BCU1205B'),  -- Educational Technology
  ('BCU1201B'),  -- General Teaching-Learning Methods
  ('BEF1203B'),  -- Historical Foundations of Education
  ('BEF1202B'),  -- Philosophical Foundations of Education
  ('BEE1206B'),  -- Professional Ethics
  ('BEF1207B');  -- Special Needs in Education

INSERT INTO campus_dynamics_portal.acad_course_registration
       (regno, courseID, acad_year, semester, course_status, prog_id, stud_session,
        provisional_marks_status, mark_stage, registration_type,
        lecturer_status, lecturer_status_by, lecturer_status_at, edit_audit_trail)
SELECT @reg, t.course_code, @year, @sem, 'REGULAR', 'BED(P)', 'INSERVICE',
       'pending', 'NOT_ENTERED', 'NORMAL',
       'APPROVED', @actor, NOW(),
       CONCAT('Restored 2026-08-27 from acad_activity_log (registered ',
              '2026-05-18 09:47:49, ACAD=2026/2027 SEM=2) and the student''s ',
              '2026/2027 Session 2 examination permit.')
  FROM tmp_restore_courses t
 WHERE NOT EXISTS (
        SELECT 1 FROM campus_dynamics_portal.acad_course_registration c
         WHERE TRIM(c.regno) = @reg AND TRIM(c.courseID) = t.course_code
           AND c.acad_year = @year AND c.semester = @sem);

-- ---------------------------------------------------------------------------
-- 3. Move her surviving bills onto the semester she is actually registered for.
--
--    Her two live bills are tagged 2025/2026 sem 2 — the duplicate semester that
--    was deleted — while the matching 2026/2027 bills were removed on 27 Aug.
--    Re-tagging rather than re-creating keeps her billed total at 434,000; a
--    restore of the deleted pair would double-bill her to 868,000. Amounts,
--    item codes and dates are untouched, so her balance stays at 30,000 credit.
-- ---------------------------------------------------------------------------
UPDATE campus_dynamics_accounts.fin_studentfeestracking
   SET acadyear = @year, semester = @sem,
       detail = REPLACE(detail, '2025/2026', '2026/2027')
 WHERE TRIM(regno) = @reg
   AND trans_type = 'Bill'
   AND acadyear = '2025/2026'
   AND semester = 2;

-- ---------------------------------------------------------------------------
-- 4. Verification.
-- ---------------------------------------------------------------------------
SELECT '--- 1. semester registration (expect 1 row, 2026/2027 sem 2 yr 1) ---' AS check_1;
SELECT ID, acad_year, semester, studyyear, regstatus, registeredBy
  FROM campus_dynamics.acad_registration WHERE TRIM(regno) = @reg;

SELECT '--- 2. course registrations (expect 10) ---' AS check_2;
SELECT COUNT(*) AS courses_restored,
       GROUP_CONCAT(TRIM(courseID) ORDER BY courseID SEPARATOR ' ') AS list
  FROM campus_dynamics_portal.acad_course_registration
 WHERE TRIM(regno) = @reg AND acad_year = @year AND semester = @sem;

SELECT '--- 3. every restored course is in the BED(P) yr1 sem2 curriculum (expect 10) ---' AS check_3;
SELECT COUNT(DISTINCT TRIM(c.courseID)) AS courses_matching_curriculum
  FROM campus_dynamics_portal.acad_course_registration c
  JOIN campus_dynamics.acad_programmecourses pc
    ON TRIM(pc.course_code) = TRIM(c.courseID) AND TRIM(pc.progcode) = 'BED(P)'
   AND pc.study_year = 1 AND pc.semester = 2
 WHERE TRIM(c.regno) = @reg AND c.acad_year = @year AND c.semester = @sem;

SELECT '--- 4. finance unchanged in total: 434,000 billed / 464,000 paid / 30,000 credit ---' AS check_4;
SELECT SUM(IF(trans_type = 'Bill', amount, 0))    AS billed,
       SUM(IF(trans_type = 'Payment', amount, 0)) AS paid,
       SUM(IF(trans_type = 'Payment', amount, 0))
         - SUM(IF(trans_type = 'Bill', amount, 0)) AS credit
  FROM campus_dynamics_accounts.fin_studentfeestracking WHERE TRIM(regno) = @reg;

SELECT '--- 5. bills now sit on the registered semester (expect both 2026/2027 sem 2) ---' AS check_5;
SELECT TID, acadyear, semester, item_code, amount, trans_type
  FROM campus_dynamics_accounts.fin_studentfeestracking
 WHERE TRIM(regno) = @reg ORDER BY trans_date;

SELECT '--- 6. she now matches her cohort ---' AS check_6;
SELECT TRIM(r.regno) AS regno, r.acad_year, r.semester, r.studyyear, r.regstatus,
       (SELECT COUNT(*) FROM campus_dynamics_portal.acad_course_registration c
         WHERE TRIM(c.regno) = TRIM(r.regno) AND c.acad_year = r.acad_year
           AND c.semester = r.semester) AS courses
  FROM campus_dynamics.acad_registration r
 WHERE TRIM(r.regno) IN ('MRU2026004388','MRU2026004387','MRU2026004597','MRU2026004598')
   AND r.acad_year = '2026/2027' AND r.semester = 2
 ORDER BY regno;
