USE campus_dynamics;
-- Restore Ordinary Diploma (Electrical) course names supplied from the
-- student's original paper transcript (MRU08/U/ODEE/338). 32 ARCHIVED codes.
-- Names UPPERCASED to match the catalogue convention (5975/5975 ACTIVE = upper).
DROP TABLE IF EXISTS bak_ode_names_20260730;
CREATE TABLE bak_ode_names_20260730 AS SELECT courseID, courseName, courseDescription FROM acad_course WHERE courseID IN ('ODC1107','ODE1101','ODE1102','ODE1103','ODE1104','ODE1105','ODE1106','ODE1108','ODE1201','ODE1202','ODE1203','ODE1204','ODE1205','ODE1206','ODE1207','ODE1208','ODE1209','ODE2101','ODE2102','ODE2103','ODE2104','ODE2105','ODE2106','ODE2108','ODE2109','ODE2111','ODE2201','ODE2202','ODE2203','ODE2205','ODE2206','ODE2212');
UPDATE acad_course SET courseName='BASIC WORKSHOP TECHNOLOGY AND PRACTICE I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODC1107' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ESSENTIAL MATHEMATICS I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1101' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='TECHNICAL DRAWING I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1102' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='MECHANICAL ENGINEERING SCIENCE I (STATICS)', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1103' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL ENGINEERING SCIENCE I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1104' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='SOLAR PV TECHNOLOGY AND PRACTICE I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1105' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRONICS I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1106' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL POWER TECHNOLOGY AND PRACTICE I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1108' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ESSENTIAL MATHEMATICS II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1201' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='TECHNICAL DRAWING II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1202' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='MECHANICAL ENGINEERING SCIENCE II (MATERIALS)', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1203' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL ENGINEERING SCIENCE II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1204' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='SOLAR PV TECHNOLOGY AND PRACTICE II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1205' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRONICS II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1206' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='BASIC WORKSHOP TECHNOLOGY AND PRACTICE II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1207' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL POWER TECHNOLOGY AND PRACTICE II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1208' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ENGLISH AND LIBERAL STUDIES I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE1209' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ESSENTIAL MATHEMATICS III', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2101' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL ENGINEERING DRAWING I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2102' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='MECHANICAL ENGINEERING SCIENCE III (DYNAMICS)', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2103' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL ENGINEERING SCIENCE III', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2104' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='DIGITAL TECHNIQUES I', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2105' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRONICS III', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2106' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL POWER TECHNOLOGY AND PRACTICE III', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2108' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ENGLISH AND LIBERAL STUDIES II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2109' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='BUSINESS KNOWLEDGE', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2111' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ESSENTIAL MATHEMATICS IV', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2201' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRICAL ENGINEERING DRAWING II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2202' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='MECHANICAL ENGINEERING SCIENCE IV (FLUIDS)', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2203' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='DIGITAL TECHNIQUES II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2205' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='ELECTRONICS IV', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2206' AND course_state='ARCHIVED';
UPDATE acad_course SET courseName='INDUSTRIAL TRAINING II', courseDescription='Legacy Ordinary Diploma course; name restored 2026-07-30 from student original transcript (MRU08/U/ODEE/338).' WHERE courseID='ODE2212' AND course_state='ARCHIVED';
SELECT courseID, courseName, CreditUnit FROM acad_course WHERE courseID IN ('ODC1107','ODE1101','ODE1102','ODE1103','ODE1104','ODE1105','ODE1106','ODE1108','ODE1201','ODE1202','ODE1203','ODE1204','ODE1205','ODE1206','ODE1207','ODE1208','ODE1209','ODE2101','ODE2102','ODE2103','ODE2104','ODE2105','ODE2106','ODE2108','ODE2109','ODE2111','ODE2201','ODE2202','ODE2203','ODE2205','ODE2206','ODE2212') ORDER BY courseID;
